### ISSUE TITLE
conversion to onnx then trt

### ISSUE THREAD

**Issue by cwlinghk** [openpifpaf/openpifpaf#431]
I exported shufflenet2k16.onnx from export_onnx.py
Then used onnx2trt converted the onnx to trt without any error msg.
But when I load the engine and run, I received  

[TensorRT] ERROR: ../rtExt/cuda/pointwiseV2Helpers.h (538) - Cuda Error in launchPwgenKernel: 400 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception

Any ideas? Thank you very much.

**Comment by svenkreiss** [comment]
Unfortunately no. We have continuous tests for the onnx export, including a test that runs the exported model through onnxruntime and verifies its output. But there is nothing for the trt step. We don't have access to a cuda device during our tests and trt cannot run without it as far as I know.

**Comment by thancaocuong** [comment]
@cwlinghk  please tell me which version of TensorRT you are using? I have tested with TensorRT 7.0 and it works

**Comment by cwlinghk** [comment]
> @cwlinghk please tell me which version of TensorRT you are using? I have tested with TensorRT 7.0 and it works

I tried TensorRT 7.2.2 with rtx 3070
and TensorRT 7.1.3 with jetson agx

It is strange that I can run the converted trt from these two exported onnx models:
https://github.com/neuralet/models/tree/master/ONNX/openpifpaf_12a4

**Comment by thancaocuong** [comment]
@cwlinghk I dont use your given repo to convert model. I use master branch of openpifpaf to convert it directly to onnx and then use trt_exec to convert it to tensorRT engine
Here are these instructions
```bash
python3 -m openpifpaf.export_onnx --input-width [INPUT_WIDTH] --input-height [INPUT_HEIGHT] --checkpoint [checkpoint_path] --outfile [FILE]
/usr/src/tensorrt/bin/trtexec --onnx=[onnx FILE] --fp16 --batch=1 --saveEngine=pose.engine  --workspace=25
```
for **trtexec**, you can use tensorRT docker from [this](https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_20-03.html#rel_20-03). 
Then you can use tensorrt with python to load and inference with engine

**Comment by cwlinghk** [comment]
Thanks, I solved the problem now

**Comment by HoangTienDuc** [comment]
@thancaocuong Hello a Cuong. 
I followed openpifpaf tensorrt [repo](https://github.com/HoangTienDuc/PifPaf-TensorRT-Pose-Estimation). But i don't have any jetson right now, so i decide to install and run openpifpaf on my GPU (RTX 2080ti) with tensorrt 7.2.1.
I cannot run tensorrt openpifpaf code, but base on that, i implement it by myself to use tensorrt 7.2.1.
These are no error during my inference, but the result is very bad. 
![result](https://user-images.githubusercontent.com/53229746/136680535-c8a2efe3-b654-4b56-8e6f-a55e702df36a.jpg)

Hope you take a look my [implementation](https://gist.github.com/HoangTienDuc/b15c3f45a560f8613a4f495fbe727c4b), and give me a help.
Origin image

Thank you!

**Comment by agrija9** [comment]
> @cwlinghk I dont use your given repo to convert model. I use master branch of openpifpaf to convert it directly to onnx and then use trt_exec to convert it to tensorRT engine Here are these instructions
> 
> ```shell
> python3 -m openpifpaf.export_onnx --input-width [INPUT_WIDTH] --input-height [INPUT_HEIGHT] --checkpoint [checkpoint_path] --outfile [FILE]
> /usr/src/tensorrt/bin/trtexec --onnx=[onnx FILE] --fp16 --batch=1 --saveEngine=pose.engine  --workspace=25
> ```
> 

@cwlinghk What version of TensorRT did you use for this? 

I am trying to do this on TensorRT 7.1.3 (Jetson Xavier) but I have a dynamic shape error:

[03/09/2022-13:24:00] [E] [TRT] Network has dynamic or shape inputs, but no optimization profile has been defined.
[03/09/2022-13:24:00] [E] [TRT] Network validation failed.
[03/09/2022-13:24:00] [E] Engine creation failed
[03/09/2022-13:24:00] [E] Engine set up failed

**Comment by thancaocuong** [comment]
@HoangTienDuc okay, I will do it when I have free time
